name: CI

on:
  push:
    branches:
      - crawler
      - har-file
      - swagger
      - brokencrystals
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * THU"

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-20.04
    container: node:16
    name: A job to run a BrightSec scan
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt update -qq --fix-missing
          apt install -y --no-install-recommends nodejs npm make g++
          npm install -g @brightsec/cli --unsafe-perm=true
          apt-get install jq -y 
          apt-get install curl -y
          
      - name: Save environment variables
        run: |
          printf "BRIGHT_TOKEN=${{ secrets.BRIGHT_TOKEN }}\nREPEATER5=${{ secrets.REPEATER5 }}\nPROJECT5=${{ secrets.PROJECT5 }}\nBC_LESSB_AUTH5=${{ secrets.BC_LESSB_AUTH5 }}" > .env
          cat .env
      - run: sleep 30s
      - name: Start Brightsec Scan 🏁
        id: start
        run: |
          SCAN_ID=$(bright-cli scan:run                                                 \
            --test csrf dom_xss header_security secret_tokens open_buckets excess_data_exposure \                
            --name "💎 Local GH BrokenCrystals for a '${GITHUB_REF##*/}' branch #${GITHUB_RUN_NUMBER}" \
            --crawler http://10.0.0.170:8090/api/config http://10.0.0.170:8090/  \
            --host-filter 10.0.0.170:8090                                 \
            --repeater ${{ secrets.REPEATER5 }}                           \
            --auth ${{ secrets.BC_LESSB_AUTH5 }}                          \ 
            --project ${{ secrets.PROJECT5 }}                             \
            --token ${{ secrets.BRIGHT_TOKEN }}                          \
            --cluster demo.brightsec.com)
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
      - name: Get the output scan url 🔗
        run: |
          printf "Scan was started, check details at https://app.brightsec.com/scans/$SCAN_ID"
      - name: Wait for issues ⏳
        run: |
          bright-cli scan:polling                 \
            --interval 30s                        \
            --timeout 10m                         \
            --token ${{ secrets.BRIGHT_TOKEN5 }}  \
            --breakpoint high_issue $SCAN_ID      \
            --cluster demo.brightsec.com
      - name: Stop Scan 🛑
        continue-on-error: true
        if: ${{ always() }}
        run: bright-cli scan:stop --token ${{ secrets.BRIGHT_TOKEN5 }} $SCAN_ID --cluster demo.brightsec.com
